### ISSUE TITLE
gh-pages branch is behind master

### ISSUE THREAD

**Issue by 0joshuaolson1** [jackaudio/jackaudio.github.com#52]
Perhaps gh-pages can be deleted and master renamed to it.

**Comment by MrMormon** [comment]
Which invites the question of which branch to make PRs to.

**Comment by mseeber** [comment]
PRs go to master. The gh-pages branch is just for having some kind of "preview" that can be seen at https://jackaudio.github.io/

TODO @mseeber:

- [ ]  update README.md
- [ ] sync gh-pages to master

**Comment by MrMormon** [comment]
The preview looks the same as the website and appears to use master. https://jackaudio.github.io/applications/ has JackSharp ([latest commit](https://github.com/jackaudio/jackaudio.github.com/blob/master/applications/index.md)) and gh-pages [does not](https://github.com/jackaudio/jackaudio.github.com/blob/gh-pages/applications/index.md).

**Comment by mseeber** [comment]
jackaudio.org is probably not synced yet with master, since it is not hosted on GitHub directly, but pulled from master to a different host. Thats the reason in is out of sync.

I remember, the gh-pages branch shows only for a specific url in case of this repository, it is not that much relevant for this repository, but helps people who fork it, so they can preview their changes.
In the GitHub Pages Help/Documentation this is explained more in detail.

**Comment by mseeber** [comment]
I am going to keep master and gh-pages in sync in the future, so i guess this is resolved.
